@echo off
rem Generated by `memory-industry setup service`. Not edited by hand.
rem
rem Task Scheduler cannot set environment variables, and this binary reads no
rem .env file of its own. Without this launcher the task starts a daemon with
rem no DATABASE_URL and no token, and on Windows nothing reports that: the task
rem 'ran', and the only symptom is a daemon that never appears.
setlocal
rem Same failure, one step earlier: `for /f` over a file that is not there runs
rem its body zero times and falls through, so a missing env file starts exactly
rem the empty daemon those lines describe. The exit code below is what reaches
rem Task Scheduler's Last Run Result; falling through is what reports success.
if not exist "%LOCALAPPDATA%\MemoryIndustry\memory-industry.env" (
  echo memory-industry: %LOCALAPPDATA%\MemoryIndustry\memory-industry.env is not there.
  echo Nothing would set DATABASE_URL or the bearer token, so the daemon would start
  echo deaf and the task would report success. Run: memory-industry setup service --apply
  exit /b 1
)
for /f "usebackq eol=# tokens=1,* delims==" %%a in ("%LOCALAPPDATA%\MemoryIndustry\memory-industry.env") do set "%%a=%%b"
"%LOCALAPPDATA%\MemoryIndustry\memory-industry.exe" serve 127.0.0.1:8787
